import uuid
from datetime import datetime, timezone
from sqlalchemy import (
    Column, String, Integer, Float, DateTime, ForeignKey, Enum as SQLEnum, Text
)
from sqlalchemy.orm import relationship

from app.db.base import Base
from app.models.enums import (
    CopilotRole,
    CopilotPlanStatus,
    CopilotToolStatus,
    DataStatusType,
)


class CopilotSession(Base):
    """
    Persistent conversational session for the AI Chartering Copilot.
    Maintains session-level maritime context (cargo request, vessel, voyage),
    historical exchanges, and execution traces.
    """
    __tablename__ = "copilot_sessions"

    id = Column(String(36), primary_key=True, index=True, default=lambda: str(uuid.uuid4()))
    title = Column(String(255), nullable=False, default="Chartering Inquiry")
    
    # Active Maritime Context References
    cargo_request_id = Column(String(36), ForeignKey("cargo_requirements.id", ondelete="SET NULL"), nullable=True, index=True)
    vessel_id = Column(String(36), ForeignKey("vessels.id", ondelete="SET NULL"), nullable=True, index=True)
    voyage_id = Column(String(36), nullable=True, index=True)
    
    # Serialized active context snapshot (origin, destination, laycan, etc.)
    context_json = Column(Text, nullable=True)

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    # Relationships
    cargo_request = relationship("CargoRequirement")
    vessel = relationship("Vessel")
    messages = relationship("CopilotMessage", back_populates="session", cascade="all, delete-orphan", order_by="CopilotMessage.created_at")
    plans = relationship("CopilotPlan", back_populates="session", cascade="all, delete-orphan")
    tool_calls = relationship("CopilotToolCall", back_populates="session", cascade="all, delete-orphan")


class CopilotPlan(Base):
    """
    Structured execution plan generated by CharteringPlannerService.
    Sequences analytical tool calls required to answer user goals without hallucinations.
    """
    __tablename__ = "copilot_plans"

    id = Column(String(36), primary_key=True, index=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String(36), ForeignKey("copilot_sessions.id", ondelete="CASCADE"), nullable=False, index=True)
    user_goal = Column(Text, nullable=False)
    plan_json = Column(Text, nullable=False) # JSON array of planned tool executions
    status = Column(SQLEnum(CopilotPlanStatus), default=CopilotPlanStatus.PLANNED, nullable=False)

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    completed_at = Column(DateTime, nullable=True)

    session = relationship("CopilotSession", back_populates="plans")
    messages = relationship("CopilotMessage", back_populates="plan")
    tool_calls = relationship("CopilotToolCall", back_populates="plan")


class CopilotMessage(Base):
    """
    Individual chat turn within a Copilot session.
    Stores user queries, system prompts, or grounded assistant assessments
    alongside structured JSON payloads.
    """
    __tablename__ = "copilot_messages"

    id = Column(String(36), primary_key=True, index=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String(36), ForeignKey("copilot_sessions.id", ondelete="CASCADE"), nullable=False, index=True)
    role = Column(SQLEnum(CopilotRole), nullable=False)
    content = Column(Text, nullable=False) # Markdown representation
    structured_response = Column(Text, nullable=True) # Full StructuredCopilotResponse JSON

    plan_id = Column(String(36), ForeignKey("copilot_plans.id", ondelete="SET NULL"), nullable=True, index=True)

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    session = relationship("CopilotSession", back_populates="messages")
    plan = relationship("CopilotPlan", back_populates="messages")
    tool_calls = relationship("CopilotToolCall", back_populates="message")


class CopilotToolCall(Base):
    """
    Audit record of an analytical tool invocation executed during plan execution.
    Tracks execution status, timing, parameters, and errors.
    """
    __tablename__ = "copilot_tool_calls"

    id = Column(String(36), primary_key=True, index=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String(36), ForeignKey("copilot_sessions.id", ondelete="CASCADE"), nullable=False, index=True)
    message_id = Column(String(36), ForeignKey("copilot_messages.id", ondelete="SET NULL"), nullable=True, index=True)
    plan_id = Column(String(36), ForeignKey("copilot_plans.id", ondelete="SET NULL"), nullable=True, index=True)

    tool_name = Column(String(100), nullable=False, index=True)
    arguments = Column(Text, nullable=False) # JSON serialized arguments
    status = Column(SQLEnum(CopilotToolStatus), default=CopilotToolStatus.PENDING, nullable=False)

    started_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    completed_at = Column(DateTime, nullable=True)
    execution_time_ms = Column(Float, nullable=True)
    error = Column(Text, nullable=True)

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    session = relationship("CopilotSession", back_populates="tool_calls")
    message = relationship("CopilotMessage", back_populates="tool_calls")
    plan = relationship("CopilotPlan", back_populates="tool_calls")
    result = relationship("CopilotToolResult", back_populates="tool_call", uselist=False, cascade="all, delete-orphan")


class CopilotToolResult(Base):
    """
    Validated structured result returned by an analytical tool execution.
    Preserves strict data provenance (source, data_status, dataset version).
    """
    __tablename__ = "copilot_tool_results"

    id = Column(String(36), primary_key=True, index=True, default=lambda: str(uuid.uuid4()))
    tool_call_id = Column(String(36), ForeignKey("copilot_tool_calls.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    
    result_json = Column(Text, nullable=False) # Structured tool outcome JSON
    source = Column(String(100), nullable=False)
    data_status = Column(SQLEnum(DataStatusType), default=DataStatusType.SYNTHETIC, nullable=False)
    dataset_version_id = Column(String(100), nullable=True)

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    tool_call = relationship("CopilotToolCall", back_populates="result")
