from enum import Enum

class CargoType(str, Enum):
    COKING_COAL = "COKING_COAL"
    THERMAL_COAL = "THERMAL_COAL"
    PCI_COAL = "PCI_COAL"
    IRON_ORE_FINES = "IRON_ORE_FINES"
    IRON_ORE_LUMPS = "IRON_ORE_LUMPS"
    IRON_ORE_PELLETS = "IRON_ORE_PELLETS"
    LIMESTONE = "LIMESTONE"
    DOLOMITE = "DOLOMITE"
    MANGANESE_ORE = "MANGANESE_ORE"

class VesselClass(str, Enum):
    HANDYSIZE = "HANDYSIZE"
    HANDYMAX = "HANDYMAX"
    SUPRAMAX = "SUPRAMAX"
    ULTRAMAX = "ULTRAMAX"
    PANAMAX = "PANAMAX"
    KAMSARMAX = "KAMSARMAX"
    POST_PANAMAX = "POST_PANAMAX"
    CAPESIZE = "CAPESIZE"
    NEWCASTLEMAX = "NEWCASTLEMAX"

class VesselStatus(str, Enum):
    BALLAST_TRANSIT = "BALLAST_TRANSIT"
    LADEN_TRANSIT = "LADEN_TRANSIT"
    AT_ANCHORAGE = "AT_ANCHORAGE"
    BERTHED_LOADING = "BERTHED_LOADING"
    BERTHED_DISCHARGING = "BERTHED_DISCHARGING"
    WAITING_ORDERS = "WAITING_ORDERS"
    DRYDOCK_MAINTENANCE = "DRYDOCK_MAINTENANCE"

class MatchStatus(str, Enum):
    RELEVANT = "RELEVANT"
    PARTIAL = "PARTIAL"
    NOT_RELEVANT = "NOT_RELEVANT"
    UNKNOWN = "UNKNOWN"

class FeasibilityStatus(str, Enum):
    PASS = "PASS"
    CONDITIONAL = "CONDITIONAL"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"

class ConstraintSeverity(str, Enum):
    BLOCKING = "BLOCKING"
    WARNING = "WARNING"
    ADVISORY = "ADVISORY"

class RequirementStatus(str, Enum):
    DRAFT = "DRAFT"
    MARKET_SCAN = "MARKET_SCAN"
    OFFERS_INVITED = "OFFERS_INVITED"
    COMMERCIAL_EVALUATION = "COMMERCIAL_EVALUATION"
    FIXTURE_RECOMMENDED = "FIXTURE_RECOMMENDED"
    FIXED = "FIXED"
    CANCELLED = "CANCELLED"

class ForecastModelType(str, Enum):
    TFT = "TFT"
    MOVING_AVERAGE_7D = "MOVING_AVERAGE_7D"
    MOVING_AVERAGE_30D = "MOVING_AVERAGE_30D"
    PERSISTENCE_NAIVE = "PERSISTENCE_NAIVE"

class DataSourceType(str, Enum):
    PORT_AUTHORITY_OFFICIAL = "PORT_AUTHORITY_OFFICIAL"
    BERTH_MASTER = "BERTH_MASTER"
    HISTORICAL_FIXTURE = "HISTORICAL_FIXTURE"
    SAIL_INTERNAL_LOG = "SAIL_INTERNAL_LOG"
    OPERATIONAL_SNAPSHOT = "OPERATIONAL_SNAPSHOT"

class MarketRegimeType(str, Enum):
    BULL = "BULL"
    BEAR = "BEAR"
    NEUTRAL = "NEUTRAL"
    SEASONAL = "SEASONAL"

class DataStatusType(str, Enum):
    LIVE = "LIVE"
    RECENT = "RECENT"
    STALE = "STALE"
    PUBLIC = "PUBLIC"
    LICENSED = "LICENSED"
    DEMO = "DEMO"
    SYNTHETIC = "SYNTHETIC"
    UNAVAILABLE = "UNAVAILABLE"
    UNKNOWN = "UNKNOWN"
    VERIFIED = "VERIFIED"
    CALCULATED = "CALCULATED"

class ForecastRegimeAlignment(str, Enum):
    ALIGNED = "ALIGNED"
    DIVERGENT = "DIVERGENT"
    NEUTRAL = "NEUTRAL"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"

class WaitFixDecision(str, Enum):
    FIX_NOW = "FIX_NOW"
    WAIT = "WAIT"
    MONITOR = "MONITOR"
    DECISION_WINDOW_EXPIRED = "DECISION_WINDOW_EXPIRED"
    NOT_EVALUABLE = "NOT_EVALUABLE"

class DecisionConfidence(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class WaitFixScenarioType(str, Enum):
    LOW = "LOW"
    CENTRAL = "CENTRAL"
    HIGH = "HIGH"

class ContractStrategyType(str, Enum):
    SPOT = "SPOT"
    SHORT_TERM_MULTIPLE_VOYAGE = "SHORT_TERM_MULTIPLE_VOYAGE"
    MEDIUM_TERM_MULTIPLE_VOYAGE = "MEDIUM_TERM_MULTIPLE_VOYAGE"

class MarketScenarioType(str, Enum):
    BEAR = "BEAR"
    BASE = "BASE"
    BULL = "BULL"

class VesselEmploymentState(str, Enum):
    EMPLOYED = "EMPLOYED"
    VOYAGE_COMPLETING = "VOYAGE_COMPLETING"
    AVAILABLE = "AVAILABLE"
    NEXT_EMPLOYMENT_PENDING = "NEXT_EMPLOYMENT_PENDING"
    IDLE_RISK = "IDLE_RISK"
    IDLE = "IDLE"
    REPOSITIONING = "REPOSITIONING"
    ALTERNATIVE_EMPLOYMENT = "ALTERNATIVE_EMPLOYMENT"
    UNKNOWN = "UNKNOWN"

class EmploymentEventType(str, Enum):
    VOYAGE_TRANSIT = "VOYAGE_TRANSIT"
    DISCHARGE = "DISCHARGE"
    LOAD = "LOAD"
    ANCHORAGE_WAIT = "ANCHORAGE_WAIT"
    BALLAST_REPOSITION = "BALLAST_REPOSITION"
    MAINTENANCE = "MAINTENANCE"

class IdleScenarioType(str, Enum):
    EARLY_ARRIVAL = "EARLY_ARRIVAL"
    EMPLOYMENT_GAP = "EMPLOYMENT_GAP"
    PORT_DELAY = "PORT_DELAY"
    REPOSITIONING_GAP = "REPOSITIONING_GAP"
    DEMAND_GAP = "DEMAND_GAP"
    UNKNOWN = "UNKNOWN"

class RepositioningDecision(str, Enum):
    REPOSITION = "REPOSITION"
    DO_NOT_REPOSITION = "DO_NOT_REPOSITION"
    UNKNOWN = "UNKNOWN"

class DeadheadRiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    UNKNOWN = "UNKNOWN"

class EmploymentCompatibility(str, Enum):
    COMPATIBLE = "COMPATIBLE"
    PARTIAL = "PARTIAL"
    NOT_COMPATIBLE = "NOT_COMPATIBLE"
    UNKNOWN = "UNKNOWN"

class RiskType(str, Enum):
    PORT_CONGESTION = "PORT_CONGESTION"
    WEATHER = "WEATHER"
    TIDAL = "TIDAL"
    VESSEL = "VESSEL"
    PORT_OPERATION = "PORT_OPERATION"
    TIMING = "TIMING"
    IDLE = "IDLE"
    REPOSITIONING = "REPOSITIONING"
    DATA_QUALITY = "DATA_QUALITY"

class RiskSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"

class RiskStatus(str, Enum):
    ACTIVE = "ACTIVE"
    MONITORED = "MONITORED"
    MITIGATED = "MITIGATED"
    RESOLVED = "RESOLVED"
    EXPIRED = "EXPIRED"
    SIMULATED = "SIMULATED"

class TidalWindowStatus(str, Enum):
    PASS = "PASS"
    CONDITIONAL = "CONDITIONAL"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"

class CongestionIndicator(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    SEVERE = "SEVERE"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"

class CostComponentType(str, Enum):
    FREIGHT = "FREIGHT"
    BUNKER = "BUNKER"
    PORT_DUES = "PORT_DUES"
    BERTH_CHARGES = "BERTH_CHARGES"
    CARGO_HANDLING = "CARGO_HANDLING"
    PILOTAGE_TOWAGE = "PILOTAGE_TOWAGE"
    AGENCY_SUNDRIES = "AGENCY_SUNDRIES"
    TIME_CHARTER = "TIME_CHARTER"
    TIME_OPPORTUNITY = "TIME_OPPORTUNITY"
    DELAY_DEMURRAGE = "DELAY_DEMURRAGE"
    REPOSITIONING_BUNKER = "REPOSITIONING_BUNKER"
    OTHER = "OTHER"

class VoyageScenarioType(str, Enum):
    BASE = "BASE"
    LOW_COST = "LOW_COST"
    HIGH_COST = "HIGH_COST"
    DELAY = "DELAY"
    SLOW_STEAM = "SLOW_STEAM"
    FAST_TRANSIT = "FAST_TRANSIT"

class SpeedScenarioStatus(str, Enum):
    ECONOMICALLY_PREFERRED = "ECONOMICALLY_PREFERRED"
    EVALUATED = "EVALUATED"
    SUBOPTIMAL = "SUBOPTIMAL"
    SPEED_EXCEEDS_RATING = "SPEED_EXCEEDS_RATING"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class CopilotRole(str, Enum):
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class CopilotPlanStatus(str, Enum):
    PLANNED = "PLANNED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class CopilotToolStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class DecisionPipelineState(str, Enum):
    DRAFT = "DRAFT"
    VALIDATING = "VALIDATING"
    VESSEL_ANALYSIS = "VESSEL_ANALYSIS"
    PORT_ANALYSIS = "PORT_ANALYSIS"
    FREIGHT_ANALYSIS = "FREIGHT_ANALYSIS"
    MARKET_ANALYSIS = "MARKET_ANALYSIS"
    DECISION_ANALYSIS = "DECISION_ANALYSIS"
    CONTRACT_ANALYSIS = "CONTRACT_ANALYSIS"
    RISK_ANALYSIS = "RISK_ANALYSIS"
    ECONOMIC_ANALYSIS = "ECONOMIC_ANALYSIS"
    READY = "READY"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"


class DecisionReadinessStatus(str, Enum):
    READY = "READY"
    CONDITIONAL = "CONDITIONAL"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"


