"""create_wait_fix_tables

Revision ID: d045ad11ea04
Revises: fea706f38f32
Create Date: 2026-09-18 20:38:31.154418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd045ad11ea04'
down_revision: Union[str, Sequence[str], None] = 'fea706f38f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wait_fix_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cargo_request_id', sa.String(length=36), nullable=True),
    sa.Column('origin_port_id', sa.String(length=36), nullable=False),
    sa.Column('destination_port_id', sa.String(length=36), nullable=False),
    sa.Column('cargo_type', sa.Enum('COKING_COAL', 'THERMAL_COAL', 'PCI_COAL', 'IRON_ORE_FINES', 'IRON_ORE_LUMPS', 'IRON_ORE_PELLETS', 'LIMESTONE', 'DOLOMITE', 'MANGANESE_ORE', name='cargotype'), nullable=False),
    sa.Column('cargo_quantity', sa.Float(), nullable=False),
    sa.Column('vessel_class', sa.Enum('HANDYSIZE', 'HANDYMAX', 'SUPRAMAX', 'ULTRAMAX', 'PANAMAX', 'KAMSARMAX', 'POST_PANAMAX', 'CAPESIZE', 'NEWCASTLEMAX', name='vesselclass'), nullable=False),
    sa.Column('current_freight_rate', sa.Float(), nullable=False),
    sa.Column('p10_rate', sa.Float(), nullable=False),
    sa.Column('p50_rate', sa.Float(), nullable=False),
    sa.Column('p90_rate', sa.Float(), nullable=False),
    sa.Column('expected_wait_rate', sa.Float(), nullable=False),
    sa.Column('expected_fix_cost', sa.Float(), nullable=False),
    sa.Column('expected_wait_cost', sa.Float(), nullable=False),
    sa.Column('expected_modeled_difference', sa.Float(), nullable=False),
    sa.Column('wait_option_value', sa.Float(), nullable=True),
    sa.Column('decision', sa.Enum('FIX_NOW', 'WAIT', 'MONITOR', 'DECISION_WINDOW_EXPIRED', 'NOT_EVALUABLE', name='waitfixdecision'), nullable=False),
    sa.Column('decision_confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='decisionconfidence'), nullable=False),
    sa.Column('decision_deadline', sa.DateTime(), nullable=True),
    sa.Column('remaining_days', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.String(length=36), nullable=True),
    sa.Column('regime_id', sa.String(length=36), nullable=True),
    sa.Column('model_version_id', sa.String(length=100), nullable=True),
    sa.Column('dataset_version_id', sa.String(length=100), nullable=True),
    sa.Column('data_status', sa.Enum('LIVE', 'RECENT', 'STALE', 'PUBLIC', 'LICENSED', 'DEMO', 'SYNTHETIC', 'UNAVAILABLE', 'UNKNOWN', name='datastatustype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_request_id'], ['cargo_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['origin_port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wait_fix_analyses_cargo_request_id'), 'wait_fix_analyses', ['cargo_request_id'], unique=False)
    op.create_index(op.f('ix_wait_fix_analyses_created_at'), 'wait_fix_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_wait_fix_analyses_decision'), 'wait_fix_analyses', ['decision'], unique=False)
    op.create_index(op.f('ix_wait_fix_analyses_destination_port_id'), 'wait_fix_analyses', ['destination_port_id'], unique=False)
    op.create_index(op.f('ix_wait_fix_analyses_id'), 'wait_fix_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_wait_fix_analyses_origin_port_id'), 'wait_fix_analyses', ['origin_port_id'], unique=False)
    op.create_table('wait_fix_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_name', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('freight_cost', sa.Float(), nullable=False),
    sa.Column('difference_vs_fix', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['wait_fix_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wait_fix_scenarios_analysis_id'), 'wait_fix_scenarios', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_wait_fix_scenarios_id'), 'wait_fix_scenarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wait_fix_scenarios_id'), table_name='wait_fix_scenarios')
    op.drop_index(op.f('ix_wait_fix_scenarios_analysis_id'), table_name='wait_fix_scenarios')
    op.drop_table('wait_fix_scenarios')
    op.drop_index(op.f('ix_wait_fix_analyses_origin_port_id'), table_name='wait_fix_analyses')
    op.drop_index(op.f('ix_wait_fix_analyses_id'), table_name='wait_fix_analyses')
    op.drop_index(op.f('ix_wait_fix_analyses_destination_port_id'), table_name='wait_fix_analyses')
    op.drop_index(op.f('ix_wait_fix_analyses_decision'), table_name='wait_fix_analyses')
    op.drop_index(op.f('ix_wait_fix_analyses_created_at'), table_name='wait_fix_analyses')
    op.drop_index(op.f('ix_wait_fix_analyses_cargo_request_id'), table_name='wait_fix_analyses')
    op.drop_table('wait_fix_analyses')
    # ### end Alembic commands ###
