"""create_market_regime_tables

Revision ID: fea706f38f32
Revises: 
Create Date: 2026-09-18 20:21:15.693199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea706f38f32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraint_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraint_versions_entity_id'), 'constraint_versions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_constraint_versions_id'), 'constraint_versions', ['id'], unique=False)
    op.create_table('ports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unlocode', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('coast', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('channel_max_draft_m', sa.Float(), nullable=True),
    sa.Column('channel_max_loa_m', sa.Float(), nullable=True),
    sa.Column('channel_max_beam_m', sa.Float(), nullable=True),
    sa.Column('tide_range_m', sa.Float(), nullable=True),
    sa.Column('night_navigation', sa.Boolean(), nullable=True),
    sa.Column('tug_requirement_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ports_id'), 'ports', ['id'], unique=False)
    op.create_index(op.f('ix_ports_name'), 'ports', ['name'], unique=False)
    op.create_index(op.f('ix_ports_unlocode'), 'ports', ['unlocode'], unique=True)
    op.create_table('vessels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('imo_number', sa.String(length=10), nullable=False),
    sa.Column('vessel_name', sa.String(length=100), nullable=False),
    sa.Column('vessel_class', sa.Enum('HANDYSIZE', 'HANDYMAX', 'SUPRAMAX', 'ULTRAMAX', 'PANAMAX', 'KAMSARMAX', 'POST_PANAMAX', 'CAPESIZE', 'NEWCASTLEMAX', name='vesselclass'), nullable=False),
    sa.Column('flag', sa.String(length=50), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('call_sign', sa.String(length=20), nullable=True),
    sa.Column('classification_society', sa.String(length=50), nullable=True),
    sa.Column('is_snapshot_vessel', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessels_id'), 'vessels', ['id'], unique=False)
    op.create_index(op.f('ix_vessels_imo_number'), 'vessels', ['imo_number'], unique=True)
    op.create_index(op.f('ix_vessels_vessel_class'), 'vessels', ['vessel_class'], unique=False)
    op.create_index(op.f('ix_vessels_vessel_name'), 'vessels', ['vessel_name'], unique=False)
    op.create_table('berths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('port_id', sa.String(length=36), nullable=False),
    sa.Column('berth_code', sa.String(length=30), nullable=False),
    sa.Column('berth_name', sa.String(length=100), nullable=False),
    sa.Column('berth_type', sa.String(length=50), nullable=False),
    sa.Column('max_loa_m', sa.Float(), nullable=True),
    sa.Column('max_beam_m', sa.Float(), nullable=True),
    sa.Column('max_draft_m', sa.Float(), nullable=True),
    sa.Column('max_air_draft_m', sa.Float(), nullable=True),
    sa.Column('max_dwt', sa.Float(), nullable=True),
    sa.Column('discharge_rate_tpd', sa.Float(), nullable=True),
    sa.Column('loading_rate_tpd', sa.Float(), nullable=True),
    sa.Column('equipment_summary', sa.String(length=255), nullable=True),
    sa.Column('night_berthing', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_berths_berth_code'), 'berths', ['berth_code'], unique=False)
    op.create_index(op.f('ix_berths_id'), 'berths', ['id'], unique=False)
    op.create_index(op.f('ix_berths_port_id'), 'berths', ['port_id'], unique=False)
    op.create_table('cargo_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_code', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('cargo_type', sa.Enum('COKING_COAL', 'THERMAL_COAL', 'PCI_COAL', 'IRON_ORE_FINES', 'IRON_ORE_LUMPS', 'IRON_ORE_PELLETS', 'LIMESTONE', 'DOLOMITE', 'MANGANESE_ORE', name='cargotype'), nullable=False),
    sa.Column('quantity_mt', sa.Float(), nullable=False),
    sa.Column('tolerance_pct', sa.Float(), nullable=True),
    sa.Column('load_port_id', sa.String(length=36), nullable=False),
    sa.Column('discharge_port_id', sa.String(length=36), nullable=False),
    sa.Column('laycan_start', sa.DateTime(), nullable=False),
    sa.Column('laycan_end', sa.DateTime(), nullable=False),
    sa.Column('target_freight_usd_pmt', sa.Float(), nullable=True),
    sa.Column('max_vessel_age_years', sa.Integer(), nullable=True),
    sa.Column('preferred_vessel_classes', sa.String(length=100), nullable=True),
    sa.Column('gear_requirement', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'MARKET_SCAN', 'OFFERS_INVITED', 'COMMERCIAL_EVALUATION', 'FIXTURE_RECOMMENDED', 'FIXED', 'CANCELLED', name='requirementstatus'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discharge_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['load_port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_requirements_cargo_type'), 'cargo_requirements', ['cargo_type'], unique=False)
    op.create_index(op.f('ix_cargo_requirements_id'), 'cargo_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_cargo_requirements_requirement_code'), 'cargo_requirements', ['requirement_code'], unique=True)
    op.create_table('feasibility_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vessel_id', sa.String(length=36), nullable=False),
    sa.Column('port_id', sa.String(length=36), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(), nullable=True),
    sa.Column('overall_status', sa.Enum('PASS', 'CONDITIONAL', 'FAIL', 'UNKNOWN', name='feasibilitystatus'), nullable=False),
    sa.Column('evaluated_berths_count', sa.Integer(), nullable=True),
    sa.Column('passing_berths_count', sa.Integer(), nullable=True),
    sa.Column('summary_narrative', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feasibility_runs_id'), 'feasibility_runs', ['id'], unique=False)
    op.create_index(op.f('ix_feasibility_runs_port_id'), 'feasibility_runs', ['port_id'], unique=False)
    op.create_index(op.f('ix_feasibility_runs_vessel_id'), 'feasibility_runs', ['vessel_id'], unique=False)
    op.create_table('freight_routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_code', sa.String(length=50), nullable=False),
    sa.Column('origin_port_id', sa.String(length=36), nullable=False),
    sa.Column('destination_port_id', sa.String(length=36), nullable=False),
    sa.Column('default_vessel_class', sa.Enum('HANDYSIZE', 'HANDYMAX', 'SUPRAMAX', 'ULTRAMAX', 'PANAMAX', 'KAMSARMAX', 'POST_PANAMAX', 'CAPESIZE', 'NEWCASTLEMAX', name='vesselclass'), nullable=False),
    sa.Column('distance_nm', sa.Float(), nullable=False),
    sa.Column('typical_duration_days', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['origin_port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_routes_id'), 'freight_routes', ['id'], unique=False)
    op.create_index(op.f('ix_freight_routes_route_code'), 'freight_routes', ['route_code'], unique=True)
    op.create_table('market_regimes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('origin_port_id', sa.String(length=36), nullable=False),
    sa.Column('destination_port_id', sa.String(length=36), nullable=False),
    sa.Column('trade_lane', sa.String(length=100), nullable=False),
    sa.Column('cargo_type', sa.Enum('COKING_COAL', 'THERMAL_COAL', 'PCI_COAL', 'IRON_ORE_FINES', 'IRON_ORE_LUMPS', 'IRON_ORE_PELLETS', 'LIMESTONE', 'DOLOMITE', 'MANGANESE_ORE', name='cargotype'), nullable=False),
    sa.Column('vessel_class', sa.Enum('HANDYSIZE', 'HANDYMAX', 'SUPRAMAX', 'ULTRAMAX', 'PANAMAX', 'KAMSARMAX', 'POST_PANAMAX', 'CAPESIZE', 'NEWCASTLEMAX', name='vesselclass'), nullable=False),
    sa.Column('regime', sa.Enum('BULL', 'BEAR', 'NEUTRAL', 'SEASONAL', name='marketregimetype'), nullable=False),
    sa.Column('regime_probability', sa.Float(), nullable=False),
    sa.Column('bull_probability', sa.Float(), nullable=False),
    sa.Column('bear_probability', sa.Float(), nullable=False),
    sa.Column('neutral_probability', sa.Float(), nullable=False),
    sa.Column('seasonal_probability', sa.Float(), nullable=False),
    sa.Column('regime_start_date', sa.DateTime(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('model_version_id', sa.String(length=50), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=50), nullable=False),
    sa.Column('data_status', sa.Enum('LIVE', 'RECENT', 'STALE', 'PUBLIC', 'LICENSED', 'DEMO', 'SYNTHETIC', 'UNAVAILABLE', 'UNKNOWN', name='datastatustype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['origin_port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_regimes_destination_port_id'), 'market_regimes', ['destination_port_id'], unique=False)
    op.create_index(op.f('ix_market_regimes_detected_at'), 'market_regimes', ['detected_at'], unique=False)
    op.create_index(op.f('ix_market_regimes_id'), 'market_regimes', ['id'], unique=False)
    op.create_index(op.f('ix_market_regimes_origin_port_id'), 'market_regimes', ['origin_port_id'], unique=False)
    op.create_index(op.f('ix_market_regimes_regime'), 'market_regimes', ['regime'], unique=False)
    op.create_index(op.f('ix_market_regimes_trade_lane'), 'market_regimes', ['trade_lane'], unique=False)
    op.create_table('operational_snapshot_vessels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vessel_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_vessel_name', sa.String(length=100), nullable=False),
    sa.Column('observed_handled_cargo_mt', sa.Float(), nullable=False),
    sa.Column('cargo_type', sa.String(length=50), nullable=False),
    sa.Column('discharge_port_code', sa.String(length=30), nullable=False),
    sa.Column('discharge_berth_code', sa.String(length=30), nullable=True),
    sa.Column('observation_date', sa.DateTime(), nullable=False),
    sa.Column('data_integrity_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_snapshot_vessels_id'), 'operational_snapshot_vessels', ['id'], unique=False)
    op.create_index(op.f('ix_operational_snapshot_vessels_vessel_id'), 'operational_snapshot_vessels', ['vessel_id'], unique=False)
    op.create_table('port_constraints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('port_id', sa.String(length=36), nullable=False),
    sa.Column('constraint_type', sa.String(length=50), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('limit_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.Enum('BLOCKING', 'WARNING', 'ADVISORY', name='constraintseverity'), nullable=True),
    sa.Column('condition_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_constraints_id'), 'port_constraints', ['id'], unique=False)
    op.create_index(op.f('ix_port_constraints_port_id'), 'port_constraints', ['port_id'], unique=False)
    op.create_table('port_data_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('port_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.Enum('PORT_AUTHORITY_OFFICIAL', 'BERTH_MASTER', 'HISTORICAL_FIXTURE', 'SAIL_INTERNAL_LOG', 'OPERATIONAL_SNAPSHOT', name='datasourcetype'), nullable=False),
    sa.Column('doc_reference', sa.String(length=100), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_data_sources_id'), 'port_data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_port_data_sources_port_id'), 'port_data_sources', ['port_id'], unique=False)
    op.create_table('vessel_availabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vessel_id', sa.String(length=36), nullable=False),
    sa.Column('current_status', sa.Enum('BALLAST_TRANSIT', 'LADEN_TRANSIT', 'AT_ANCHORAGE', 'BERTHED_LOADING', 'BERTHED_DISCHARGING', 'WAITING_ORDERS', 'DRYDOCK_MAINTENANCE', name='vesselstatus'), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('current_port_name', sa.String(length=100), nullable=True),
    sa.Column('destination_port_name', sa.String(length=100), nullable=True),
    sa.Column('open_port_name', sa.String(length=100), nullable=True),
    sa.Column('open_date_start', sa.DateTime(), nullable=True),
    sa.Column('open_date_end', sa.DateTime(), nullable=True),
    sa.Column('eta_open_port', sa.DateTime(), nullable=True),
    sa.Column('data_confidence', sa.String(length=20), nullable=True),
    sa.Column('source_evidence', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vessel_id')
    )
    op.create_index(op.f('ix_vessel_availabilities_id'), 'vessel_availabilities', ['id'], unique=False)
    op.create_table('vessel_particulars',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vessel_id', sa.String(length=36), nullable=False),
    sa.Column('summer_dwt', sa.Float(), nullable=True),
    sa.Column('summer_draft_m', sa.Float(), nullable=True),
    sa.Column('loa_m', sa.Float(), nullable=True),
    sa.Column('beam_m', sa.Float(), nullable=True),
    sa.Column('depth_m', sa.Float(), nullable=True),
    sa.Column('gross_tonnage', sa.Float(), nullable=True),
    sa.Column('net_tonnage', sa.Float(), nullable=True),
    sa.Column('grain_capacity_cbm', sa.Float(), nullable=True),
    sa.Column('bale_capacity_cbm', sa.Float(), nullable=True),
    sa.Column('holds_hatches_count', sa.String(length=20), nullable=True),
    sa.Column('gear_summary', sa.String(length=100), nullable=True),
    sa.Column('speed_ballast_knots', sa.Float(), nullable=True),
    sa.Column('speed_laden_knots', sa.Float(), nullable=True),
    sa.Column('consumption_laden_mtpd', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('unverified_fields', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vessel_id')
    )
    op.create_index(op.f('ix_vessel_particulars_id'), 'vessel_particulars', ['id'], unique=False)
    op.create_table('berth_constraints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('berth_id', sa.String(length=36), nullable=False),
    sa.Column('constraint_type', sa.String(length=50), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('limit_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.Enum('BLOCKING', 'WARNING', 'ADVISORY', name='constraintseverity'), nullable=True),
    sa.Column('condition_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_berth_constraints_berth_id'), 'berth_constraints', ['berth_id'], unique=False)
    op.create_index(op.f('ix_berth_constraints_id'), 'berth_constraints', ['id'], unique=False)
    op.create_table('cargo_handling_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('vessel_id', sa.String(length=36), nullable=True),
    sa.Column('port_id', sa.String(length=36), nullable=False),
    sa.Column('berth_id', sa.String(length=36), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('quantity_handled_mt', sa.Float(), nullable=False),
    sa.Column('average_rate_tpd', sa.Float(), nullable=True),
    sa.Column('weather_delays_hours', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['cargo_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_handling_logs_id'), 'cargo_handling_logs', ['id'], unique=False)
    op.create_index(op.f('ix_cargo_handling_logs_requirement_id'), 'cargo_handling_logs', ['requirement_id'], unique=False)
    op.create_table('feasibility_berth_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feasibility_run_id', sa.String(length=36), nullable=False),
    sa.Column('berth_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'CONDITIONAL', 'FAIL', 'UNKNOWN', name='feasibilitystatus'), nullable=False),
    sa.Column('draft_clearance_m', sa.Float(), nullable=True),
    sa.Column('loa_clearance_m', sa.Float(), nullable=True),
    sa.Column('beam_clearance_m', sa.Float(), nullable=True),
    sa.Column('estimated_turnaround_days', sa.Float(), nullable=True),
    sa.Column('summary_explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feasibility_run_id'], ['feasibility_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feasibility_berth_results_berth_id'), 'feasibility_berth_results', ['berth_id'], unique=False)
    op.create_index(op.f('ix_feasibility_berth_results_feasibility_run_id'), 'feasibility_berth_results', ['feasibility_run_id'], unique=False)
    op.create_index(op.f('ix_feasibility_berth_results_id'), 'feasibility_berth_results', ['id'], unique=False)
    op.create_table('forecast_backtest_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('model_type', sa.Enum('TFT', 'MOVING_AVERAGE_7D', 'MOVING_AVERAGE_30D', 'PERSISTENCE_NAIVE', name='forecastmodeltype'), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('test_start_date', sa.DateTime(), nullable=False),
    sa.Column('test_end_date', sa.DateTime(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('mape', sa.Float(), nullable=False),
    sa.Column('directional_accuracy_pct', sa.Float(), nullable=False),
    sa.Column('pinball_loss_p10', sa.Float(), nullable=False),
    sa.Column('pinball_loss_p50', sa.Float(), nullable=False),
    sa.Column('pinball_loss_p90', sa.Float(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['freight_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_backtest_results_id'), 'forecast_backtest_results', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_backtest_results_route_id'), 'forecast_backtest_results', ['route_id'], unique=False)
    op.create_table('freight_forecasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('vessel_class', sa.Enum('HANDYSIZE', 'HANDYMAX', 'SUPRAMAX', 'ULTRAMAX', 'PANAMAX', 'KAMSARMAX', 'POST_PANAMAX', 'CAPESIZE', 'NEWCASTLEMAX', name='vesselclass'), nullable=False),
    sa.Column('model_type', sa.Enum('TFT', 'MOVING_AVERAGE_7D', 'MOVING_AVERAGE_30D', 'PERSISTENCE_NAIVE', name='forecastmodeltype'), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('predicted_p10', sa.Float(), nullable=False),
    sa.Column('predicted_p50', sa.Float(), nullable=False),
    sa.Column('predicted_p90', sa.Float(), nullable=False),
    sa.Column('confidence_pct', sa.Float(), nullable=True),
    sa.Column('volatility_index', sa.Float(), nullable=True),
    sa.Column('feature_attributions', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['freight_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_forecasts_id'), 'freight_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_freight_forecasts_route_id'), 'freight_forecasts', ['route_id'], unique=False)
    op.create_index(op.f('ix_freight_forecasts_target_date'), 'freight_forecasts', ['target_date'], unique=False)
    op.create_table('freight_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('observation_date', sa.DateTime(), nullable=False),
    sa.Column('freight_rate_usd_pmt', sa.Float(), nullable=False),
    sa.Column('bunker_vlsfo_usd', sa.Float(), nullable=True),
    sa.Column('bunker_mgo_usd', sa.Float(), nullable=True),
    sa.Column('baltic_index_value', sa.Float(), nullable=True),
    sa.Column('congestion_origin_days', sa.Float(), nullable=True),
    sa.Column('congestion_dest_days', sa.Float(), nullable=True),
    sa.Column('is_interpolated', sa.Boolean(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['freight_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_observations_id'), 'freight_observations', ['id'], unique=False)
    op.create_index(op.f('ix_freight_observations_observation_date'), 'freight_observations', ['observation_date'], unique=False)
    op.create_index(op.f('ix_freight_observations_route_id'), 'freight_observations', ['route_id'], unique=False)
    op.create_table('market_regime_transitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('market_regime_id', sa.String(length=36), nullable=False),
    sa.Column('previous_regime', sa.Enum('BULL', 'BEAR', 'NEUTRAL', 'SEASONAL', name='marketregimetype'), nullable=False),
    sa.Column('new_regime', sa.Enum('BULL', 'BEAR', 'NEUTRAL', 'SEASONAL', name='marketregimetype'), nullable=False),
    sa.Column('transition_date', sa.DateTime(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('trigger_features', sa.Text(), nullable=True),
    sa.Column('model_version_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_regime_id'], ['market_regimes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_regime_transitions_id'), 'market_regime_transitions', ['id'], unique=False)
    op.create_index(op.f('ix_market_regime_transitions_market_regime_id'), 'market_regime_transitions', ['market_regime_id'], unique=False)
    op.create_index(op.f('ix_market_regime_transitions_transition_date'), 'market_regime_transitions', ['transition_date'], unique=False)
    op.create_table('vessel_match_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(), nullable=True),
    sa.Column('total_evaluated', sa.Integer(), nullable=True),
    sa.Column('relevant_count', sa.Integer(), nullable=True),
    sa.Column('partial_count', sa.Integer(), nullable=True),
    sa.Column('not_relevant_count', sa.Integer(), nullable=True),
    sa.Column('unknown_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['cargo_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessel_match_runs_id'), 'vessel_match_runs', ['id'], unique=False)
    op.create_index(op.f('ix_vessel_match_runs_requirement_id'), 'vessel_match_runs', ['requirement_id'], unique=False)
    op.create_table('feasibility_rule_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('berth_result_id', sa.String(length=36), nullable=False),
    sa.Column('rule_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'CONDITIONAL', 'FAIL', 'UNKNOWN', name='feasibilitystatus'), nullable=False),
    sa.Column('limit_value', sa.Float(), nullable=True),
    sa.Column('vessel_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('is_blocking', sa.Boolean(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['berth_result_id'], ['feasibility_berth_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feasibility_rule_evaluations_berth_result_id'), 'feasibility_rule_evaluations', ['berth_result_id'], unique=False)
    op.create_index(op.f('ix_feasibility_rule_evaluations_id'), 'feasibility_rule_evaluations', ['id'], unique=False)
    op.create_table('vessel_match_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_run_id', sa.String(length=36), nullable=False),
    sa.Column('vessel_id', sa.String(length=36), nullable=False),
    sa.Column('overall_status', sa.Enum('RELEVANT', 'PARTIAL', 'NOT_RELEVANT', 'UNKNOWN', name='matchstatus'), nullable=False),
    sa.Column('summary_explanation', sa.Text(), nullable=False),
    sa.Column('is_data_complete', sa.Boolean(), nullable=True),
    sa.Column('missing_fields', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['match_run_id'], ['vessel_match_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessel_match_candidates_id'), 'vessel_match_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_vessel_match_candidates_match_run_id'), 'vessel_match_candidates', ['match_run_id'], unique=False)
    op.create_index(op.f('ix_vessel_match_candidates_vessel_id'), 'vessel_match_candidates', ['vessel_id'], unique=False)
    op.create_table('vessel_match_rule_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('rule_name', sa.String(length=50), nullable=False),
    sa.Column('rule_category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('RELEVANT', 'PARTIAL', 'NOT_RELEVANT', 'UNKNOWN', name='matchstatus'), nullable=False),
    sa.Column('evaluated_value', sa.String(length=100), nullable=True),
    sa.Column('required_value', sa.String(length=100), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['vessel_match_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessel_match_rule_results_candidate_id'), 'vessel_match_rule_results', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_vessel_match_rule_results_id'), 'vessel_match_rule_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vessel_match_rule_results_id'), table_name='vessel_match_rule_results')
    op.drop_index(op.f('ix_vessel_match_rule_results_candidate_id'), table_name='vessel_match_rule_results')
    op.drop_table('vessel_match_rule_results')
    op.drop_index(op.f('ix_vessel_match_candidates_vessel_id'), table_name='vessel_match_candidates')
    op.drop_index(op.f('ix_vessel_match_candidates_match_run_id'), table_name='vessel_match_candidates')
    op.drop_index(op.f('ix_vessel_match_candidates_id'), table_name='vessel_match_candidates')
    op.drop_table('vessel_match_candidates')
    op.drop_index(op.f('ix_feasibility_rule_evaluations_id'), table_name='feasibility_rule_evaluations')
    op.drop_index(op.f('ix_feasibility_rule_evaluations_berth_result_id'), table_name='feasibility_rule_evaluations')
    op.drop_table('feasibility_rule_evaluations')
    op.drop_index(op.f('ix_vessel_match_runs_requirement_id'), table_name='vessel_match_runs')
    op.drop_index(op.f('ix_vessel_match_runs_id'), table_name='vessel_match_runs')
    op.drop_table('vessel_match_runs')
    op.drop_index(op.f('ix_market_regime_transitions_transition_date'), table_name='market_regime_transitions')
    op.drop_index(op.f('ix_market_regime_transitions_market_regime_id'), table_name='market_regime_transitions')
    op.drop_index(op.f('ix_market_regime_transitions_id'), table_name='market_regime_transitions')
    op.drop_table('market_regime_transitions')
    op.drop_index(op.f('ix_freight_observations_route_id'), table_name='freight_observations')
    op.drop_index(op.f('ix_freight_observations_observation_date'), table_name='freight_observations')
    op.drop_index(op.f('ix_freight_observations_id'), table_name='freight_observations')
    op.drop_table('freight_observations')
    op.drop_index(op.f('ix_freight_forecasts_target_date'), table_name='freight_forecasts')
    op.drop_index(op.f('ix_freight_forecasts_route_id'), table_name='freight_forecasts')
    op.drop_index(op.f('ix_freight_forecasts_id'), table_name='freight_forecasts')
    op.drop_table('freight_forecasts')
    op.drop_index(op.f('ix_forecast_backtest_results_route_id'), table_name='forecast_backtest_results')
    op.drop_index(op.f('ix_forecast_backtest_results_id'), table_name='forecast_backtest_results')
    op.drop_table('forecast_backtest_results')
    op.drop_index(op.f('ix_feasibility_berth_results_id'), table_name='feasibility_berth_results')
    op.drop_index(op.f('ix_feasibility_berth_results_feasibility_run_id'), table_name='feasibility_berth_results')
    op.drop_index(op.f('ix_feasibility_berth_results_berth_id'), table_name='feasibility_berth_results')
    op.drop_table('feasibility_berth_results')
    op.drop_index(op.f('ix_cargo_handling_logs_requirement_id'), table_name='cargo_handling_logs')
    op.drop_index(op.f('ix_cargo_handling_logs_id'), table_name='cargo_handling_logs')
    op.drop_table('cargo_handling_logs')
    op.drop_index(op.f('ix_berth_constraints_id'), table_name='berth_constraints')
    op.drop_index(op.f('ix_berth_constraints_berth_id'), table_name='berth_constraints')
    op.drop_table('berth_constraints')
    op.drop_index(op.f('ix_vessel_particulars_id'), table_name='vessel_particulars')
    op.drop_table('vessel_particulars')
    op.drop_index(op.f('ix_vessel_availabilities_id'), table_name='vessel_availabilities')
    op.drop_table('vessel_availabilities')
    op.drop_index(op.f('ix_port_data_sources_port_id'), table_name='port_data_sources')
    op.drop_index(op.f('ix_port_data_sources_id'), table_name='port_data_sources')
    op.drop_table('port_data_sources')
    op.drop_index(op.f('ix_port_constraints_port_id'), table_name='port_constraints')
    op.drop_index(op.f('ix_port_constraints_id'), table_name='port_constraints')
    op.drop_table('port_constraints')
    op.drop_index(op.f('ix_operational_snapshot_vessels_vessel_id'), table_name='operational_snapshot_vessels')
    op.drop_index(op.f('ix_operational_snapshot_vessels_id'), table_name='operational_snapshot_vessels')
    op.drop_table('operational_snapshot_vessels')
    op.drop_index(op.f('ix_market_regimes_trade_lane'), table_name='market_regimes')
    op.drop_index(op.f('ix_market_regimes_regime'), table_name='market_regimes')
    op.drop_index(op.f('ix_market_regimes_origin_port_id'), table_name='market_regimes')
    op.drop_index(op.f('ix_market_regimes_id'), table_name='market_regimes')
    op.drop_index(op.f('ix_market_regimes_detected_at'), table_name='market_regimes')
    op.drop_index(op.f('ix_market_regimes_destination_port_id'), table_name='market_regimes')
    op.drop_table('market_regimes')
    op.drop_index(op.f('ix_freight_routes_route_code'), table_name='freight_routes')
    op.drop_index(op.f('ix_freight_routes_id'), table_name='freight_routes')
    op.drop_table('freight_routes')
    op.drop_index(op.f('ix_feasibility_runs_vessel_id'), table_name='feasibility_runs')
    op.drop_index(op.f('ix_feasibility_runs_port_id'), table_name='feasibility_runs')
    op.drop_index(op.f('ix_feasibility_runs_id'), table_name='feasibility_runs')
    op.drop_table('feasibility_runs')
    op.drop_index(op.f('ix_cargo_requirements_requirement_code'), table_name='cargo_requirements')
    op.drop_index(op.f('ix_cargo_requirements_id'), table_name='cargo_requirements')
    op.drop_index(op.f('ix_cargo_requirements_cargo_type'), table_name='cargo_requirements')
    op.drop_table('cargo_requirements')
    op.drop_index(op.f('ix_berths_port_id'), table_name='berths')
    op.drop_index(op.f('ix_berths_id'), table_name='berths')
    op.drop_index(op.f('ix_berths_berth_code'), table_name='berths')
    op.drop_table('berths')
    op.drop_index(op.f('ix_vessels_vessel_name'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_vessel_class'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_imo_number'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_id'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_ports_unlocode'), table_name='ports')
    op.drop_index(op.f('ix_ports_name'), table_name='ports')
    op.drop_index(op.f('ix_ports_id'), table_name='ports')
    op.drop_table('ports')
    op.drop_index(op.f('ix_constraint_versions_id'), table_name='constraint_versions')
    op.drop_index(op.f('ix_constraint_versions_entity_id'), table_name='constraint_versions')
    op.drop_table('constraint_versions')
    # ### end Alembic commands ###
